name: Add names to README
run-name: ${{ github.actor }} is editing README 
on: [push]
jobs:
  Add-To-README:
    runs-on: ubuntu latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - run: echo "The ${{ github.repository }} repository has been cloned."
      - name: Add text to file
        run: echo "Zachary Brosius; Gus Alston" >> README.md
      - name: Add file
        run: git add README.md
      - name: Commit the file
        run: git commit -m "Updated README with member names"
      - name: Push changes
        run: git push
